### PR TITLE
Add compatibility for PHP8

### PR DESCRIPTION
**Pull request by genesiscz**

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you make the tests run on PHP 8 as well?

**Comment by genesiscz** [comment]
image

**Comment by freekmurze** [comment]
Could you add PHP 8 to this lists, so our automated tests run on PHP 8 as well?
https://github.com/spatie/laravel-varnish/blob/39b0065c6e0d6535fa9202a28a5ae82729cfb72f/.github/workflows/run-tests.yml#L12

**Comment by genesiscz** [comment]
Yeah older versions of laravel fail as they don't have support for PHP8. What now?

**Comment by freekmurze** [comment]
Seems like Laravel 5.8 doesn't like PHP 8. Could you drop support for Laravel 5.8 from composer.json and remove it from the test configuration?

**Comment by genesiscz** [comment]
Ready (y)

**Comment by freekmurze** [comment]
Perfect, thank you!

**Pull request merged**
